global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: zerotrust-fl-coordinator
    static_configs:
      - targets:
          - coordinator:9464

  - job_name: zerotrust-fl-workers
    static_configs:
      - targets:
          - benign-worker-1:9465
          - benign-worker-2:9465
          - benign-worker-3:9465
          - malicious-worker-1:9465

  - job_name: zerotrust-fl-simulator
    static_configs:
      - targets:
          - fl-simulator:9466
