# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import fl_service_pb2 as fl__service__pb2

GRPC_GENERATED_VERSION = '1.83.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in fl_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class CoordinatorServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RegisterNode = channel.unary_unary(
                '/zerotrust.fl.v1.CoordinatorService/RegisterNode',
                request_serializer=fl__service__pb2.RegisterNodeRequest.SerializeToString,
                response_deserializer=fl__service__pb2.RegisterNodeResponse.FromString,
                _registered_method=True)
        self.Heartbeat = channel.unary_unary(
                '/zerotrust.fl.v1.CoordinatorService/Heartbeat',
                request_serializer=fl__service__pb2.HeartbeatRequest.SerializeToString,
                response_deserializer=fl__service__pb2.HeartbeatResponse.FromString,
                _registered_method=True)
        self.GetGlobalModel = channel.unary_unary(
                '/zerotrust.fl.v1.CoordinatorService/GetGlobalModel',
                request_serializer=fl__service__pb2.GetGlobalModelRequest.SerializeToString,
                response_deserializer=fl__service__pb2.GlobalModel.FromString,
                _registered_method=True)
        self.SubmitLocalUpdate = channel.unary_unary(
                '/zerotrust.fl.v1.CoordinatorService/SubmitLocalUpdate',
                request_serializer=fl__service__pb2.SubmitLocalUpdateRequest.SerializeToString,
                response_deserializer=fl__service__pb2.SubmitLocalUpdateResponse.FromString,
                _registered_method=True)
        self.RotateRegistration = channel.unary_unary(
                '/zerotrust.fl.v1.CoordinatorService/RotateRegistration',
                request_serializer=fl__service__pb2.RotateRegistrationRequest.SerializeToString,
                response_deserializer=fl__service__pb2.RotateRegistrationResponse.FromString,
                _registered_method=True)
        self.RevokeRegistration = channel.unary_unary(
                '/zerotrust.fl.v1.CoordinatorService/RevokeRegistration',
                request_serializer=fl__service__pb2.RevokeRegistrationRequest.SerializeToString,
                response_deserializer=fl__service__pb2.RevokeRegistrationResponse.FromString,
                _registered_method=True)


class CoordinatorServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def RegisterNode(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Heartbeat(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetGlobalModel(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SubmitLocalUpdate(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RotateRegistration(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RevokeRegistration(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CoordinatorServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RegisterNode': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterNode,
                    request_deserializer=fl__service__pb2.RegisterNodeRequest.FromString,
                    response_serializer=fl__service__pb2.RegisterNodeResponse.SerializeToString,
            ),
            'Heartbeat': grpc.unary_unary_rpc_method_handler(
                    servicer.Heartbeat,
                    request_deserializer=fl__service__pb2.HeartbeatRequest.FromString,
                    response_serializer=fl__service__pb2.HeartbeatResponse.SerializeToString,
            ),
            'GetGlobalModel': grpc.unary_unary_rpc_method_handler(
                    servicer.GetGlobalModel,
                    request_deserializer=fl__service__pb2.GetGlobalModelRequest.FromString,
                    response_serializer=fl__service__pb2.GlobalModel.SerializeToString,
            ),
            'SubmitLocalUpdate': grpc.unary_unary_rpc_method_handler(
                    servicer.SubmitLocalUpdate,
                    request_deserializer=fl__service__pb2.SubmitLocalUpdateRequest.FromString,
                    response_serializer=fl__service__pb2.SubmitLocalUpdateResponse.SerializeToString,
            ),
            'RotateRegistration': grpc.unary_unary_rpc_method_handler(
                    servicer.RotateRegistration,
                    request_deserializer=fl__service__pb2.RotateRegistrationRequest.FromString,
                    response_serializer=fl__service__pb2.RotateRegistrationResponse.SerializeToString,
            ),
            'RevokeRegistration': grpc.unary_unary_rpc_method_handler(
                    servicer.RevokeRegistration,
                    request_deserializer=fl__service__pb2.RevokeRegistrationRequest.FromString,
                    response_serializer=fl__service__pb2.RevokeRegistrationResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'zerotrust.fl.v1.CoordinatorService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('zerotrust.fl.v1.CoordinatorService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class CoordinatorService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def RegisterNode(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/zerotrust.fl.v1.CoordinatorService/RegisterNode',
            fl__service__pb2.RegisterNodeRequest.SerializeToString,
            fl__service__pb2.RegisterNodeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Heartbeat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/zerotrust.fl.v1.CoordinatorService/Heartbeat',
            fl__service__pb2.HeartbeatRequest.SerializeToString,
            fl__service__pb2.HeartbeatResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetGlobalModel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/zerotrust.fl.v1.CoordinatorService/GetGlobalModel',
            fl__service__pb2.GetGlobalModelRequest.SerializeToString,
            fl__service__pb2.GlobalModel.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SubmitLocalUpdate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/zerotrust.fl.v1.CoordinatorService/SubmitLocalUpdate',
            fl__service__pb2.SubmitLocalUpdateRequest.SerializeToString,
            fl__service__pb2.SubmitLocalUpdateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RotateRegistration(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/zerotrust.fl.v1.CoordinatorService/RotateRegistration',
            fl__service__pb2.RotateRegistrationRequest.SerializeToString,
            fl__service__pb2.RotateRegistrationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RevokeRegistration(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/zerotrust.fl.v1.CoordinatorService/RevokeRegistration',
            fl__service__pb2.RevokeRegistrationRequest.SerializeToString,
            fl__service__pb2.RevokeRegistrationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
